# Generated by Django 5.2.6 on 2025-09-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_remove_dumppost_photo_dumppostimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="dumppost",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dumppost",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
